encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("newentry", views.newentry, name="newentry"),
    path("random", views.randomentry, name="random"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("search", views.search, name="search")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.html import strip_tags
from django.contrib import messages
from markdown2 import Markdown
import random

from . import util

class NewEntryTitle(forms.Form):
    title = forms.CharField(label="Entry Name", max_length=120)

class NewEntryContent(forms.Form):
    content = forms.CharField(label="",
                              widget=forms.Textarea(attrs={'placeholder': '# Lorem ipsum\n\n**Lorem ipsum** dolor sit amet...', 'style': 'height: 500px'}))

class SearchForm(forms.Form):
    query = forms.CharField(label="",
                            widget=forms.TextInput(attrs={'placeholder': "Search the encyclopedia"}))

class EditContent(forms.Form):
    content = forms.CharField(label="",
                            widget=forms.Textarea(attrs={'style': 'height: 500px'}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def newentry(request):
    if request.method == "POST":
        formT = NewEntryTitle(request.POST)
        formC = NewEntryContent(request.POST)
        if formT.is_valid() and formC.is_valid():
            title = formT.cleaned_data["title"]
            content = formC.cleaned_data["content"]
            if title in util.list_entries():
                messages.error(request, "That entry already exists!")
                return redirect(reverse("encyclopedia:newentry"))
            else:
                util.save_entry(title, content)
                return redirect(f"wiki/{title}")
        else:
            messages.error(request, "Something went wrong. Please try again.")
            return redirect("encyclopedia/newentry.html")
        
    return render(request, "encyclopedia/newentry.html", {
        "formT": NewEntryTitle(),
        "formC": NewEntryContent()
    })


def entry(request, title):
    markdown = Markdown()
    if title in util.list_entries():
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": markdown.convert(util.get_entry(title))
        })
    else:
        return render(request, "encyclopedia/404.html")
    
    
def edit(request, title):
    content = util.get_entry(title)
    if request.method == "POST":
        formE = EditContent(request.POST)
        if formE.is_valid():
            content = formE.cleaned_data["content"]
            util.save_entry(title, content)
        else:
            messages.error(request, "Something went wrong. Please try again.")
        return redirect(f"../../wiki/{title}")
        
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "formE": EditContent(initial={"content": strip_tags(content)})
    })


def randomentry(request):
    title = random.choice(util.list_entries())
    return redirect(f"wiki/{title}")


def search(request):
    if request.method == "POST":
        formQ = SearchForm(request.POST)
        searchhits = 0
        if formQ.is_valid():
            query = formQ.cleaned_data["query"]
            if query in util.list_entries():
                title = query
                return redirect(f"wiki/{title}")
            elif util.search_entries(query) == None:
                searchresults = None
            else:
                searchresults = util.search_entries(query)
                for result in searchresults:
                    searchhits += 1
            
        return render(request, "encyclopedia/search.html", {
                    "searchresults": searchresults,
                    "query": query,
                    "searchhits": searchhits
        })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }} 
{% endblock %}

{% block body %}
    <h1>Edit {{ title }}</h1>
    <h6>Use Markdown formatting.</h6>

    {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        <div class="textboxC">
            <p>{{ formE }}</p>
        </div>
        <input class="button" type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% for message in messages %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
{% endfor %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ content|safe }}
    <a href="{{ title }}/edit"><button class="button" value="{{ title }}">Edit</button></a>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    {{ formQ }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newarticle.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a New Entry 
{% endblock %}

{% block body %}
    <h1>Create a New Entry</h1>
    <form action="{% url 'encyclopedia:newarticle' %}" method="post">
        {% csrf_token %}
        {{ formT }}
        <p>{{ formC }}</p>
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/newentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a New Entry 
{% endblock %}

{% block body %}
    <h1>Create a New Entry</h1>
    <h6>Use Markdown formatting.</h6><br>

    {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    
    <form class="textbox" action="{% url 'encyclopedia:newentry' %}" method="post">
        {% csrf_token %}
        <div class="textboxT">
            {{ formT }}
        </div>

        
        <div class="textboxC">
            <p>{{ formC }}</p>
        </div>
        <input class="button" type="submit">
    </form>

    
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search results</h1>
    {% if searchhits == 0 %}
        <h5>Your search returned no results.</h5>
    {% else %}
        <h5>Your search for "<i>{{ query }}</i>" returned {{ searchhits }} results:</h5>
    {% endif %}
    <ul>
        {% for result in searchresults %}
             <li><a href="wiki/{{ result }}">{{ result }}</a></li>
        {% endfor %} 
    </ul>
{% endblock %}